sudo: false
dist: trusty

addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-contrib-9.3

env:
  global:
    - SIMPLIFIED_TEST_DATABASE="postgres://simplified_test:test@localhost:5432/simplified_core_test"
    - ES_VERSION="6.4.0"

services:
  - postgresql
  - docker

language: python

python:
  - "2.7"

cache: pip

before_install:
  - pip install --upgrade pip
  - pip install "setuptools>=44.1.0"
  # Setup elasticsearch for integration testing in docker
  - docker run -d -p 9200:9200 -e "discovery.type=single-node" --name es elasticsearch:$ES_VERSION
  - docker exec es elasticsearch-plugin install analysis-icu
  - docker restart es

install:
  - pip install -r requirements.txt
  - python -m textblob.download_corpora

before_script:
  - psql -c 'create user simplified_test;' -U postgres
  - psql -c 'create database simplified_core_test;' -U postgres
  - psql -c 'grant all privileges on database simplified_core_test to simplified_test;' -U postgres
  - psql -c 'create extension pgcrypto;' -U postgres -d simplified_core_test

script:
  - wget -q --waitretry=1 --retry-connrefused -T 60 -O - http://127.0.0.1:9200
  - ./test
